#travis for android is still in beta...
language: android
jdk: oraclejdk8
sudo: false
os: 
    - linux

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-23
    - extra-android-m2repository

before_install:
 - chmod +x gradlew
